### ISSUE TITLE
Graphic view errors in Korean(foreign languages)

### ISSUE THREAD

**Issue by slowdive14** [maximevaillancourt/digital-garden-jekyll-template#100]
**Describe the bug**
Thank you so much for developing such a wonderful template. It's a free template, but it seems to be almost similar to a fee. However, if I write either the file name or the title of the frontmatter in Korean, there is an error in the graphic view that cannot be properly connected. I'm not sure if it's just Korean or other foreign languages, but if you have time, please revise it. Thank you again for developing such a wonderful template

**To reproduce**

**Expected behavior**

**Screenshots**
my obsidian graphic view like this(In this case, both 'front matter title' and 'file name' are in Korean.) 
![image](https://user-images.githubusercontent.com/100013214/158284583-5886ab18-08e0-4525-b8da-a562e3457e65.png)

web graphic view like this(my site address: https://slowdive.netlify.app/)
![image](https://user-images.githubusercontent.com/100013214/158284666-2dc00cc1-6498-437c-8fb5-5a4f3fbf63ff.png)

**Desktop (please complete the following information):**
 - Operating system: Window 10
 - Ruby version: [e.g. Ruby 2.7.1]

**Comment by maximevaillancourt** [comment]
Thanks for the bug report. This problem is now resolved. You may now [sync your fork with the upstream](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) to get the fix in your fork. Cheers! :raised_hands:

**Comment by slowdive14** [comment]
The problem has been solved. Thank you very much.
