### ISSUE TITLE
<!DOCTYPE> tag being generated with content

### ISSUE THREAD

**Issue by jazibobs** [maximevaillancourt/digital-garden-jekyll-template#116]
**Describe the bug**
An additional <!DOCTYPE> tag being generated when Jekyll is rendering a pages main content

**To reproduce**
1. Go to https://digital-garden-jekyll-template.netlify.app/your-first-note
2. Click on 'View Source'
3. Scroll down to line 60
4. See error:
```
<div id="notes-entry-container">
    <content>

      <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body>

<h3 id="welcome">Welcome!</h3>
```

**Expected behavior**
No additional `DOCTYPE` tags to be embedded in the HTML

**Desktop (please complete the following information):**
 - Operating system: Pop!_OS 22.04 LTS (based on Ubuntu)
 - Web browser: Firefox 100.0.1 (64-bit)

**Comment by maximevaillancourt** [comment]
Resolved in #136.
