### ISSUE TITLE
Issues rendering on github pages

### ISSUE THREAD

**Issue by Am3ra** [maximevaillancourt/digital-garden-jekyll-template#13]
I forked this repo to use on my github-managed page, and ran into some problems. I think the issue is that github pages changes base url.

**Comment by Am3ra** [comment]
I tried to change the baseurl in a local build, faced the same problem.

**Comment by maximevaillancourt** [comment]
Thanks for the report Alan. This issue appears to be specific to GitHub Pages deployments, as those are exposed in a subpath of the `<github_username>.github.io` domain name.
