### ISSUE TITLE
Failed to build: liquid exception

### ISSUE THREAD

**Issue by Adimac93** [maximevaillancourt/digital-garden-jekyll-template#133]
```
Liquid Exception: Could not locate the included file 'notes_graph.json' in any of ["/github/workspace/_includes", "/usr/local/bundle/gems/jekyll-theme-primer-0.6.0/_includes"]. Ensure it exists in one of those directories and is not a symlink as those are not allowed in safe mode. in /_layouts/note.html
[1746](https://github.com/Adimac93/Adimac93.github.io/actions/runs/3107652040/jobs/5036012202#step:4:1747)
/usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/tags/include.rb:121:in `locate_include_file': Could not locate the included file 'notes_graph.json' in any of ["/github/workspace/_includes", "/usr/local/bundle/gems/jekyll-theme-primer-0.6.0/_includes"]. Ensure it exists in one of those directories and is not a symlink as those are not allowed in safe mode. (IOError)
```
Why this is happening while deploying on Github pages?
Indeed there is no file called `notes_graph.json` and it's even excluded, what am I missing?

**Comment by maximevaillancourt** [comment]
[`notes_graph.json` is generated by a custom Jekyll plugin I wrote](https://github.com/maximevaillancourt/digital-garden-jekyll-template/blob/7ac331a4113bac77c993856562acc2bfbde9f2f7/_plugins/bidirectional_links_generator.rb#L102), and GitHub Pages doesn't support custom Jekyll plugins.

If you want to use the graph with GitHub Pages, you may try building your garden locally using Jekyll then pushing the result to GitHub Pages. Alternatively, you may deploy your garden to Netlify ([here's a guide explaining to set this up](https://maximevaillancourt.com/blog/setting-up-your-own-digital-garden-with-jekyll)).

If you don't care about the graph, you can simply remove it from this layout, [as explained here](https://github.com/maximevaillancourt/digital-garden-jekyll-template/discussions/132#discussioncomment-3625772).

`notes_graph.json` is indeed "excluded" in the Jekyll configuration: this is to prevent Jekyll from recomputing the site infinitely ([more details here](https://github.com/maximevaillancourt/digital-garden-jekyll-template/issues/22)).

Have fun!

**Comment by Adimac93** [comment]
Thanks!

**Comment by Adimac93** [comment]
Any recommendations how to render LaTeX with jekyll?

**Comment by maximevaillancourt** [comment]
[This](https://stackoverflow.com/questions/26275645/how-to-support-latex-in-github-pages) may help!
