### ISSUE TITLE
`note.html` breaks with `{{ content }}`

### ISSUE THREAD

**Issue by HFulcher** [maximevaillancourt/digital-garden-jekyll-template#139]
**Describe the bug**
When serving the Jekyll site any page that is based off a markdown note pushes any html tag after `{{ content }}` outside of the `<main>` tag. It would seem that something with the generation of the html from `{{ content }}` is breaking the html.

**To reproduce**
1. In `note.html` add a `<p>` tag with text under `{{ content }}`
2. Run `bundle exec jekyll serve`
3. Navigate to a note page and open inspector
4. See that the `<p>` tag is pushed outside `<main>` and exists at top level of `<body>`

**Expected behavior**
Tags after `{{ content }}` should keep within the appropriate parent tag.

**Desktop (please complete the following information):**
 - Operating system: macOS 11.3.1
 - Ruby version: 3.0.0

**Comment by HFulcher** [comment]
I should add that this breaks the linked notes sidebar which is how I discovered the issue in the first place.

The `side` tag gets pushed outside of main where it can't be seen by the notes container to handle the grid layout.

**Comment by HFulcher** [comment]
Doing some more digging, it seems that the problem lies with setting `open_external_links_in_new_tab` to `true` in `_config.yml`. I've disabled it for now, the issue may be to do with the fact I have restructured the collections to fit having a blog as well but this issue seems to be present in the site as is without any changes.

**Comment by maximevaillancourt** [comment]
Hello! Thanks for the bug report. I'm having trouble replicating it though, and added a counter-example on the demo website in https://github.com/maximevaillancourt/digital-garden-jekyll-template/commit/76ac51bf7696c6b2a02852a2578666a51f393cb6:

https://github.com/maximevaillancourt/digital-garden-jekyll-template/blob/76ac51bf7696c6b2a02852a2578666a51f393cb6/_layouts/note.html#L14-L18

![image](https://user-images.githubusercontent.com/8457808/202936077-00df17c9-03b2-4c22-b241-9349406ea1ea.png)

Let me know if this works on your machine.

**Comment by HFulcher** [comment]
Hi @maximevaillancourt, sorry I haven't had a chance to look at this yet. I will take a look this week and let you know!

**Comment by HFulcher** [comment]
Hey @maximevaillancourt, I can confirm that the change in 76ac51b makes a line appear at the end of every note page.

**Comment by maximevaillancourt** [comment]
Excellent, thank you for reporting back. Closing this.
