### ISSUE TITLE
Graph does work properly when zoomed or moved

### ISSUE THREAD

**Issue by wbrijesh** [maximevaillancourt/digital-garden-jekyll-template#145]
**Describe the bug**
The graph at original position doesn't go away when moved or zoomed, instead two graphs are show

**To reproduce**
1. Go to [this page](https://digital-garden-jekyll-template.netlify.app/your-first-note)
2. Scroll down to bottom of the page
3. See error

**Expected behavior**
Only show one graph.

**Desktop (please complete the following information):**
 - Operating system: macOS 13.0 (22A380)
 - Ruby version: na
 - Browser: Firefox, Safari

**Comment by wbrijesh** [comment]
<img width="949" alt="Screenshot 2022-12-30 at 10 32 03 AM" src="https://user-images.githubusercontent.com/28498071/210036720-016e5d4b-8071-4c63-a1f7-3c8a2594c28e.png">

**Comment by maximevaillancourt** [comment]
Thank you for the bug report! Fixed in https://github.com/maximevaillancourt/digital-garden-jekyll-template/commit/421635612ce4a3e349704d64b74f573be76d6ede.
