### ISSUE TITLE
Strict equality causes error in console

### ISSUE THREAD

**Issue by bmann** [maximevaillancourt/digital-garden-jekyll-template#148]
I'm back using this for a new project! The notes graph wasn't working for me until I edited both instances of strict equality `===` to equality `==`, with error `SyntaxError: Invalid regular expression: missing /`.

It works for me now 🤷‍♂️

**Comment by bmann** [comment]
OK, wait, I know what happened

The markdown highlighter is running on the notes_graph file because it's included in notes `doc.content.gsub!(/==+([^ ](.*?)?[^ .=]?)==+/, "<mark>\\1</mark>")`

I'm going to add a next line for notes:

```
Jekyll::Hooks.register [:notes], :post_convert do |doc|
  next if doc.path.start_with?('_includes/')
  replace(doc)
end
```

This way, we can include the notes graph in arbitrary notes as well.

**Comment by bmann** [comment]
Yeah, I don't really know ruby, that obviously won't work, since this not a note, it's just being included _from_ a note. My hack of not using strict equality seems to work, so.....

**Comment by boundangel** [comment]
I'm getting the same syntax error. What edit did you make that you found actually worked?

**Comment by maximevaillancourt** [comment]
Thank you for the bug report, @bmann. I'm unable to replicate the bug, could you help me by providing the following information?

1. Where does `SyntaxError: Invalid regular expression: missing /` show up? Could you provide a screenshot?
2. Echoing what @boundangel asked, were you able to fix the problem? If so, how?

Thanks!

**Comment by HeySora** [comment]
@maximevaillancourt This can be simply reproduced by adding `{% include notes_graph.html %}` **inside a .md file**. Adding this in a .html file (like it is the case by default) does not exhibit this issue.

The culprit is `_plugins/markdown-highlighter.rb`, which mistakenly matches some code from notes_graph.html's JavaScript and attempts to add <mark> tags in the middle of it.

**Comment by maximevaillancourt** [comment]
Thanks everyone for your input! Fixed in #155.

**Comment by HeySora** [comment]
I wouldn't consider that fixed :(

Simply having such a piece of code in a .md file is enough to break its rendering.

In the .md file:  
![image](https://user-images.githubusercontent.com/17962248/226188325-7b1f6e0b-bf5c-48ba-9619-19f20df3ec05.png)

End result:  
![image](https://user-images.githubusercontent.com/17962248/226188420-c1edd826-1dda-4bd0-bb6a-78ca392cf8fb.png)

**Comment by maximevaillancourt** [comment]
You're entirely right: I had to run to an appointment and pushed a lazy "fix". Let me take a deeper look now. Thanks for mentioning it!

**Comment by maximevaillancourt** [comment]
I think we're in a better place with #156 now 🙂

**Comment by HeySora** [comment]
Thank you so much!! Don't feel sorry for having done a lazy fix on a Sunday lool, I quite frankly did not expect anything to be solved today.

Thank you for everything 🧡
