### ISSUE TITLE
Different Style Graphs

### ISSUE THREAD

**Issue by Am3ra** [maximevaillancourt/digital-garden-jekyll-template#16]
I wonder if it is possible to make a different style graph?

One of the reasons I point this out, is because it was recently done to create a better-styled graph using D3 in the markdown links repo:

https://github.com/tchayen/markdown-links/tree/master/static/graphs/obsidian

Cosidering that that graph is built on a javascript framework, I wonder if it should be simple to just port the code for the graph over. The only problems I imagine is importing the data.

**Comment by Am3ra** [comment]
Something I saw looking over the graph code, is that it might be possible to do two things:

- [ ] Extract the graph code from the `notes_graph.html` into a seperate `.js` file
- [ ] Create an option in the `_config.yaml` file to select which graph, with one graph selected as default

This would allow users more options, without changing usage at all. 

Any thoughts @maximevaillancourt ?

it might be possible to do these two things without even creating a new graph format, just to give more options in the future.

**Comment by maximevaillancourt** [comment]
The current graph implementation in the template is already inspired by the markdown-links repo. What would you like to see change specifically?

**Comment by Am3ra** [comment]
Yeah, I was mostly thinking about the `obsidian` graph type they recently addedd, which seems much more modern to me.
