### ISSUE TITLE
Github Sponsor

### ISSUE THREAD

**Issue by omarcostahamido** [maximevaillancourt/digital-garden-jekyll-template#178]
@maximevaillancourt 
Did you remove github sponsorship? Any reason why?

Slight tangent: i just found out about [your blog](https://maximevaillancourt.com/blog/moving-away-from-google-services-8-years-in) and it is one of the best things i've seen recently. 

thank you

**Comment by maximevaillancourt** [comment]
Thank you Omar. I removed the GitHub sponsorship option because I'm comfortable offering this template for free. Please redirect donations to a reputable charity in your area instead :)
