### ISSUE TITLE
The content tag contains HTML and BODY tags.

### ISSUE THREAD

**Issue by zaferzent** [maximevaillancourt/digital-garden-jekyll-template#196]
The content tag contains HTML and BODY tags.

I couldn't find where to remove it. I couldn't see it in the layout or includes codes.

![resim](https://github.com/maximevaillancourt/digital-garden-jekyll-template/assets/3252134/cc6e6161-84cf-43a7-98d8-428a7f758e67)

**Comment by omarcostahamido** [comment]
you need to give more context on where you found this.
share links to your fork if you will.
my silly guess is that you have notes in html instead of md.
