### ISSUE TITLE
Add support for Roam-style link syntax

### ISSUE THREAD

**Issue by maximevaillancourt** [maximevaillancourt/digital-garden-jekyll-template#2]
Suggested on Twitter by @miketannenbaum: https://twitter.com/TheRoyalTbomb/status/1265108209691394049?s=19

**Comment by MikeTannenbaum** [comment]
Hey! I actually think I figured out how to do the links. I'm not good with git but I just updated everything [here](https://github.com/MikeTannenbaum/digital-garden-jekyll-template). I take zero credit — it was all [this person](https://www.raghuveer.net/posts/extending-jekyll-markdown-syntax-using-liquid)!

**Comment by MikeTannenbaum** [comment]
I changed around lots of repos and ended up with a fresh new copy so wanted to share a link with you. https://github.com/MikeTannenbaum/my-public-mind

**Comment by maximevaillancourt** [comment]
Hey Mike! Thanks for sharing this. Glad you could get it to work using custom Liquid code.

I just added "native" support for Roam-style link syntax in this commit: https://github.com/maximevaillancourt/digital-garden-jekyll-template/commit/a0b0b12e41d10b54bff512e0fef07a15cb7986db

I'll close this issue since it is now resolved.

Cheers!
