### ISSUE TITLE
link to file name instead of title parameter using roam [[]] syntax

### ISSUE THREAD

**Issue by Am3ra** [maximevaillancourt/digital-garden-jekyll-template#20]
Currently, most of my notes do not contain a `title` parameter at the beginning. Is there a way to modify `bidirectional_links_generator.rb` or whatever is required to make this change?

**Comment by Am3ra** [comment]
I don't know anything about ruby, but it seems the only change necessary would be the regex on line 17, I'm trying to see if there's a way to only get the filename given the page

**Comment by maximevaillancourt** [comment]
Fixed in https://github.com/maximevaillancourt/digital-garden-jekyll-template/commit/f297a68cbf517ba145e35f447f90799212610f14. Thanks Alan!

**Comment by Am3ra** [comment]
Wow, Thanks maxime! Made this much easier to use! I looked at the pull, good work! Again, thanks a lot!
