### ISSUE TITLE
Jekyll keeps polling on Windows 10 - possible fix

### ISSUE THREAD

**Issue by danielvoicu** [maximevaillancourt/digital-garden-jekyll-template#22]
Hi!

First of all, thank you for this awesome template!

I've installed the template on Windows and everything went well, with the exception of an issue that seems to be somewhat common with Jekyll being run on Windows. So this isn't a bug report per se, but I'm adding this in case someone might encounter the same issue I did.

When running `bundle exec jekyll serve`, jekyll seems to go into an infinite loop, trying to regenerate the same file. I noticed that this was something related to the **notes_graph.json** file located in **_includes**.

This can be avoided by adding this:

`exclude: ["_includes/notes_graph.json"]`

to your **_config.yml** file on Windows.

I've targeted only that file, as I am not sure if Jekyll should watch all the files in that folder. If a user doesn't change them that often, I think the entire folder can be added to the exclude list.

Thanks!

**Comment by maximevaillancourt** [comment]
Thanks Daniel! I actually [added this to my own version of the template](https://github.com/maximevaillancourt/maximevaillancourt.com/commit/5cfb12ac346bf84e9d85b9a43bf11329db878763), but forgot to backport it here.

Fixing this now :slightly_smiling_face:

**Comment by ryan-p-randall** [comment]
Just wanted to thank both of you for documenting this! I'm trying to use the backlinks generator plug-in on my own site and was extremely confused as to why Jekyll kept regenerating that file, but this issue and comment let me fix the problem.

Thank you so much for your work, Maxime!
