### ISSUE TITLE
Bug with external link and new croche gray style.

### ISSUE THREAD

**Issue by fabriceliut** [maximevaillancourt/digital-garden-jekyll-template#24]
<img width="849" alt="Screenshot 2020-11-04 at 18 14 44" src="https://user-images.githubusercontent.com/7404748/98143682-b0e52880-1ec9-11eb-9b7e-de72d3db4b39.png">

**Comment by maximevaillancourt** [comment]
Thanks Fabrice. Could you share the source file (Markdown or HTML) related to the screenshot you posted? This would help me replicate the issue more easily.

**Comment by fabriceliut** [comment]
it is this page :)

---
title: Prendre soin du collectif
---

Sujet au coeur de l'[[Archipel Kyosei]] & de beaucoup d'autres collectifs qui cherchent de nouveaux modèles pour évoluer ensemble.
Dans les paradigmes habituels, le collectif est un groupe, une équipe, une entreprise ou une nation, avec tout le sens que peuvent porter ces concepts.
La question qui émerge : est-ce que ces modèles de collectifs sont adaptés pour [[Prendre soin de soi]] & [[Prendre soin du monde]] ?

> Si une entreprise "consomme" ses employés & détruit son environnement pour des objectifs purement économiques voir financiers, est-ce que c'est un modèle adapté pour la suite du développement de notre humanité ?

Le modèle archipel est un de ces modèles en émergence, en expérimentation continue. Les nouveaux modèles de gouvernance sont également très intéressant à suivre : souvent il acceptent un plus haut niveau de [[Complexité]] permettant d'être plus inclusifs, agiles, dynamiques & en accord avec leur environnement. Ils sont plus difficiles à comprendre et à appréhender mais méritent l'effort pour ceux qui se lancent dans l'aventure. Les dynamiques & rythmes individuels viennent croiser une conscience plus éguisée des enjeux à échelle globale.

> Pour exemple, le modèle Holacratique est l'un des plus connu. Il permet une gouvernance par rôle & en cercle, sortant ainsi radicalement d'une structure hiérarchique descendante. Ce nouveau fonctionnement reste assez "stricte" mais n'impose rien, il cherche à guider en dehors des habitudes.
> Vous trouverez également des ressources du côté des nouveaux modèles d'organisations étudiés par [Frédéric Laloux](https://www.babelio.com/auteur/Frederic-Laloux/257646) qui utilise la [[Spirale dynamique]] pour illustré "l'éveil" d'une organisation.

Quelques pistes également à développer prochainement :
- L'[[Entreprise Archipel]]
- L'[[Entreprise de territoire]]

**Comment by maximevaillancourt** [comment]
Thank you for raising this issue Fabrice. Fixed in https://github.com/maximevaillancourt/digital-garden-jekyll-template/pull/27. 🙂
