### ISSUE TITLE
Create netlify.toml

### ISSUE THREAD

**Issue by MichaelCurrin** [maximevaillancourt/digital-garden-jekyll-template#28]
This will make it easier for others to setup and manage the site.

```
[build]
  command = "jekyll build --trace"
  publish = "_site"
```

You can also let Netlify set these values for you in the project UI but l like to be explicit. You also get control like setting environment to be `JEKYLL_ENV=production` and adding flags like `--trace`.

**Comment by maximevaillancourt** [comment]
Neat! Thank you for the suggestion Michael. :slightly_smiling_face:
