### ISSUE TITLE
[Feature Request] Dark Mode Support

### ISSUE THREAD

**Issue by phibr0** [maximevaillancourt/digital-garden-jekyll-template#35]
Would it be possible to add a Dark Mode Toggle somewhere?

**Comment by phibr0** [comment]
I tried to change the SCSS File but i cant change the background color

**Comment by maximevaillancourt** [comment]
Hi Phillip - in your garden, try adding a `background: #black;` property to the `body` selector:

https://github.com/maximevaillancourt/digital-garden-jekyll-template/blob/becf9f381c86186b832b4cb8624ead3ea0669e23/_sass/_style.scss#L10-L24

**Comment by phibr0** [comment]
Thank you!
