### ISSUE TITLE
Adding documentation for publishing as a static site

### ISSUE THREAD

**Issue by acgillette** [maximevaillancourt/digital-garden-jekyll-template#40]
Hi Maxime! I'm really enjoying this template, and included it in my own personal website. I encountered an issue where because I was simply uploading the contents of _site to a neocities static server, the bidirectional links were not working correctly (as the link would lead to changelog instead of changelog.html). I fixed this with some tweaking of the generator, but I'm wondering if it would be useful to add to the README? Happy to do so if that is the case.

**Comment by maximevaillancourt** [comment]
Hello! Thanks for reaching out. I'm glad you find the template useful.

I think that's a great idea. If you'd like to open a pull request to add documentation explaining how you fixed the issue, I'd appreciate it a ton. ❤️

**Comment by fmoledina** [comment]
@acgillette I would be very interested in understanding what tweaks were needed in the generator as I have the same use case. Thanks.

**Comment by acgillette** [comment]
Thanks for circling back on this, I will add it to the documentation soon. Though I'm curious, is there a reason why the generator doesn't append .html/is there a situation where the outputted links would not be an html file? I could also make a pull request with my generator modifications as well, but I'm not sure if I'm missing a use case for not having the extension linked.

**Comment by phibr0** [comment]
AFAIK it's only done because the link looks better without it. I am using Netlify and it has the option (defaults to on) to prettify the links, so omitting the extension. But it probably only works if the server knows what to do

**Comment by acgillette** [comment]
Alright, well I put in a pull request with an addition to the README for anyone who is also using neocities or other servers that cannot resolve prettified links.

**Comment by maximevaillancourt** [comment]
I added a simple config option that lets you toggle this behavior in https://github.com/maximevaillancourt/digital-garden-jekyll-template/commit/9232ce3ded24e7adc7175010fb3dc39aa2a52d04. Thanks for the suggestion!
