### ISSUE TITLE
Add markdown highlight styling

### ISSUE THREAD

**Issue by fabriceliut** [maximevaillancourt/digital-garden-jekyll-template#41]
Is this possible to add this simple styling ? Thx :)

**Comment by xplosionmind** [comment]
This should be the default in Jekyll, you should simply put the text you want to highlight in [a specific liquid tag](https://github.com/rouge-ruby/rouge#jekyll "Jekyll section of ruby-rouge repository on GitHub")

**Comment by maximevaillancourt** [comment]
You should also be able to use the "triple backtick and format" syntax to highlight a piece of code.

This raw input of Ruby code wrapped in the triple backtick block, with the first triple-backticks annoted with `rb` to denote that the block contains a snippet of Ruby... 

<pre>
```rb
def foo(bar)
  "baz"
end
```
</pre>

... should generate this color-highlighted output on the HTML page:

```rb
def foo(bar)
  "baz"
end
```

---

I added a section in the first note that showcases this in more detail (see commit https://github.com/maximevaillancourt/digital-garden-jekyll-template/commit/5d190b6a97343ec1000220f28b137edb9b2374ab), see it in action here:

https://digital-garden-jekyll-template.netlify.app/your-first-note#code-syntax-highlighting
