### ISSUE TITLE
Moving and Zooming of the Graph View throws Errors

### ISSUE THREAD

**Issue by phibr0** [maximevaillancourt/digital-garden-jekyll-template#49]
If you zoom in or out of the Graph View or just move it in any direction following Error gets thrown in the Console:

```js
your-first-note:402 Uncaught TypeError: Cannot set property 'innerHTML' of null
    at SVGSVGElement.resize (your-first-note:402)
    at H.apply (d3.min.js:2)
    at kt (d3.min.js:2)
    at w.emit (d3.min.js:2)
    at w.zoom (d3.min.js:2)
    at d3.min.js:2
    at d3.min.js:2
resize @ your-first-note:402
apply @ d3.min.js:2
kt @ d3.min.js:2
emit @ d3.min.js:2
zoom @ d3.min.js:2
(anonymous) @ d3.min.js:2
(anonymous) @ d3.min.js:2
```

![image](https://user-images.githubusercontent.com/59741989/107856286-6c055200-6e27-11eb-8a52-c7637bd5e99a.png)

**Comment by Am3ra** [comment]
I've noticed this as well, but couldn't figure it out immidiately either.

On my site, I also noticed that the graph overflows to the right.

@maximevaillancourt , would you mind if we (or even me specifically) update the graph to what is currently supported by the Foam VSCode extension? Personally, I believe it looks better. 

Alternatively, we could simply fix this.

**Comment by maximevaillancourt** [comment]
Thanks for the bug report! Fixed in https://github.com/maximevaillancourt/digital-garden-jekyll-template/commit/e6e2ea29321aa9ab7e271de943e80ca264ae3dc2.

> @maximevaillancourt , would you mind if we (or even me specifically) update the graph to what is currently supported by the Foam VSCode extension? Personally, I believe it looks better.

Pull requests are welcome! :slightly_smiling_face:
