### ISSUE TITLE
Roam style brackets not working

### ISSUE THREAD

**Issue by kevindstevens1010** [maximevaillancourt/digital-garden-jekyll-template#5]
Great theme! Thank you for building. Quick question:

I am able to get the backlinks to work, but not with the Roam-style double brackets. 

My example site is here: https://stupefied-tereshkova-10b682.netlify.app/

I'm sure this is an error on my end, but my technical know-how is showing itself at this point.

**Comment by maximevaillancourt** [comment]
Hey Kevin, thanks for opening this issue. I just took a look at your [repository](https://github.com/kevindstevens1010/digital-garden-jekyll) - it looks like you're trying to use Roam-style double brackets on the Index page, which, as you discovered, is not supported. Roam-style links only work within files in the `notes/` directory (as implemented [here](https://github.com/maximevaillancourt/digital-garden-jekyll-template/blob/f62c1bc453a0f05da2e3d8e8f78f734446dc7fc6/_plugins/bidirectional_links_generator.rb#L4)).

To resolve this on the Index page, you may use regular Markdown links (using the `[this is a hyperlink](https://example.org)` syntax), or even HTML links (using the `<a href="https://example.org">this is a hyperlink</a>` syntax).

I'll see what I can do to add native support to the template though. 😃

**Comment by maximevaillancourt** [comment]
Turns it, it was quite a simple tweak ([view implementation here](https://github.com/maximevaillancourt/digital-garden-jekyll-template/commit/2436845ca4e2f0dcbee35c11304eb53fa16774c4)).

Depending on how familiar you are with Git and GitHub, you may choose to [sync your forked repository with the one we're commenting on](https://dev.to/jeremy/how-to-sync-your-fork-with-the-parent-repository-3ok1) to get the code I just added, or simply copy the code from the commit I shared above, and directly add it to your fork.

Let me know if I can help in any other way!

**Comment by kevindstevens1010** [comment]
Perfect! 

I used Github Desktop to sync my fork with your master and it worked perfectly!

**Comment by mohammedri** [comment]
Hey @maximevaillancourt , thank you for the wonderful theme - unfortunately I am facing the same problems as Kevin. 

It seems that the links work when developing locally, but when uploaded to github pages - it no longer works. 

You can see my repo here: https://github.com/mohammedri/personal-site
Am I doing anything wrong?

**Comment by mohammedri** [comment]
Hey @maximevaillancourt looks like this was an issue with Github Pages - I changed it to Netlify and it seems to be working well.

**Comment by maximevaillancourt** [comment]
Thanks for the update Mohammed, that makes sense as GitHub Pages [doesn't support custom plugins](https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll#plugins). Since this repo generates bi-directional links using a [custom plugin I wrote](https://github.com/maximevaillancourt/digital-garden-jekyll-template/blob/master/_plugins/bidirectional_links_generator.rb), GitHub Pages won't generate them. Netlify supports custom plugins, so my custom generator works there. Cheers!
