### ISSUE TITLE
clarify github pages support in config.yml

### ISSUE THREAD

**Issue by meewgumi** [maximevaillancourt/digital-garden-jekyll-template#58]
In `_config.yml`, there is a line that suggests this template is compatible with Github Pages:

> when using GitHub Pages, the baseurl should point to where GitHub Pages deploys your repository (which is usually the repository name)

However, it's not compatible with GH Pages because of the non-whitelisted plugins in the `_plugins` folder. Reading [this note on Jekyll](https://github.com/jekyll/jekyll/blob/master/docs/_docs/plugins/installation.md) suggests that GH Pages builds must be generated locally, then pushed to GH Pages. As an example, I tried to build the site on [my GH Pages repo](https://github.com/meewgumi/digital-garden-ghpages) and backlinks are broken. 

The comment in config.yml made me think it was possible to use GH Pages to build the Jekyll site. Maybe I should have known better, and the comment is fine as is, so feel free to delete this issue. But just wanted to let you know what I experienced. Thank you for making an awesome template!

**Comment by meewgumi** [comment]
Never mind! I didn't understand the difference between `site.baseurl` and `site.url`. Looks like `baseurl` should be the subdirectory and `url` is the apex domain or subdomain. Everything makes sense now!

**Comment by maximevaillancourt** [comment]
Glad to know it works! What do you suggest we change in the wording to make this clearer?

**Comment by meewgumi** [comment]
Hi @maximevaillancourt, maybe I spoke too soon—after experimenting more with an [ssh subdirectory setup](https://github.com/meewgumi/garden-dreamhost-subdirectory-test), I don't think that `baseurl` does anything for link generation. I can use it in [head.html](https://github.com/meewgumi/digital-garden-apache-template/blob/main/_includes/head.html) and I'm pretty proud of all the conditional logic I added in there to clean up metadata absolute URLs. HOWEVER, `baseurl` can't be accessed by the link generator.... I think.

I think I know where the problem is—I added Line 12 of [bidirectional_links_generator.rb](https://github.com/meewgumi/garden-dreamhost-subdirectory-test/blob/3b8951b7a398c5d66ac1af73dc8f06632f5e78b8/_plugins/bidirectional_links_generator.rb#L12) to try to fix it, but it's not working. I can't figure out how to get `baseurl` from `_config.yml` and stick it in the generated link. No matter what I try, the backlinks box doesn't generate links with the `baseurl`. [Example page here](https://garden.megu.space/test/your-first-note.html) where my directory url is `test`

When clicking a link in "Notes mentioning this note", the `baseurl` of test is missing. It should stay on `garden.megu.space/test` but that isn't happening. Instead, it's going up to `garden.megu.space` where I also have this template installed. So confusing!

Also, the wikilinks in the note body somehow have the `baseurl` twice. `https://garden.megu.space/test/test/cats.html`

For reference, here's my [_config.yml](https://github.com/meewgumi/garden-dreamhost-subdirectory-test/blob/3b8951b7a398c5d66ac1af73dc8f06632f5e78b8/_config.yml) where I've defined both `url` and `baseurl`. Feel free to use the wording I used there.

On a more philosophical note, I don't understand the purpose of `baseurl` unless it's to create links relative to the root domain. For example, introducing a permalink default of `category/slug`, where we would need each permalink link to be `href="/category2/slug2"` so you can click these links even from a category page and end up in the right place. But right now, the whole `_site` is flat so we could just remove `baseurl` and use absolute paths right?

If you know a way to fix this, please let me know, because I do want to add categories to my URL eventually.

Thanks again for making such an awesome template, I'm having a lot of fun learning Jekyll, Ruby, and Liquid with this!

**Comment by meewgumi** [comment]
Thanks @maximevaillancourt for re-opening this! Small correction to my writeup above: *relative paths, not absolute paths. Tinkering around more, I'm going to add category pages to my root directory and keep the permalinks as `/:slug`, so I'm just going to use relative URLs throughout the site. Ex: `href="category.html"` without the `/` and without needing baseurl.

I'm also okay with using this template on apex domains and subdomains only, and I'm writing a note for that in my fork. If you can figure this problem out though, I'm still curious why the `.rb` variables aren't working like I thought they would.

**Comment by omarcostahamido** [comment]
I think i found the solution. But I am really only concerned with github pages... and I think @meewgumi is addressing more complex scenarios here. I don't want run the risk of misunderstanding the issue and propose only a partial fix. So, I will open a new issue describing my problem very simply and propose a pull request with my solution. Then I will kindly ask @maximevaillancourt to decide if it does indeed fix this issue - and if not, just edit the line `-this fixes #..`
Thank you 🙏 

> _Thank you for making an awesome template!_

Reinforce!
