### ISSUE TITLE
Possible to add an optional menu?

### ISSUE THREAD

**Issue by anthrolisp** [maximevaillancourt/digital-garden-jekyll-template#68]
Is it possible to add an optional menu to this template? Thanks!

**Comment by florhizome** [comment]
I just implemented the sidebar of the “Lanyon” theme for myself, it’s pretty simple when you’re halfway into Jekyll’s framework. Could be added as a submodule, maybe. Or if @maximevaillancourt opens a wiki ppl could publish their tweaks/usage off the theme allowing for the template and maintenance to remain minimal.
