### ISSUE TITLE
Case insensitive note titles

### ISSUE THREAD

**Issue by beatricemilea** [maximevaillancourt/digital-garden-jekyll-template#69]
Hi, is there a way to make notes' titles case sensitive? Thank you! I don't know if I am the only one having this issue or not, but apart from the first letter of the notes' titles, no matter how the original files are called, the website displays all the letters in lowercase.

**Comment by timrosenberg** [comment]
You can capitalize note titles however you want in the YAML front matter.

```
---
title: cApiTAlIze aNy WaY yOu LiKe
---
```

It will render it just like that on the page.

**Comment by maximevaillancourt** [comment]
Thank you Tim. Closing as resolved.
