### ISSUE TITLE
Bi-directional linking not working for simple case?

### ISSUE THREAD

**Issue by DelonShen** [maximevaillancourt/digital-garden-jekyll-template#7]
https://silly-jepsen-d6c14e.netlify.app/hi

Says no notes mention this note however 
https://silly-jepsen-d6c14e.netlify.app/test2

mentions "hi" 

repo here:
https://github.com/DelonShen/notes

deployed on netlify

**Comment by maximevaillancourt** [comment]
Hi Delon, thanks for surfacing this--it looks like a bug indeed. I'll look into it.

**Comment by maximevaillancourt** [comment]
Just pushed a fix in https://github.com/maximevaillancourt/digital-garden-jekyll-template/commit/d8b794908ffb54f2b9be1d2fa96beda573b76380.

Depending on how familiar you are with Git and GitHub, you may choose to [sync your forked repository with the one we're commenting on](https://dev.to/jeremy/how-to-sync-your-fork-with-the-parent-repository-3ok1) to get the code I just added, or simply copy the code from the commit I shared in the paragraph above, and directly add it to your fork.

Feel free to close the issue whenever you consider the issue resolved. 🙂
