### ISSUE TITLE
wikilink to missing note beaks footnote

### ISSUE THREAD

**Issue by dennisseidel** [maximevaillancourt/digital-garden-jekyll-template#83]
**Describe the bug**
Creating wiki style links `[[something]]` to a note that doesn't exist in footnotes break the parser.

**To reproduce**
1. Create a new note e.g. `test.md`

```markdown
---
title: 'Test note '
---

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. [^1]

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. [^2]

[^1]: This links to an non existing note [[doesnot exist yet]]
[^2]: Sample footnote 2.
```

2. Start the application and go to the note.
3. See the broken footnote (see screenshot below). The footnote breaks in two parts and displays an <span> element.

**Expected behavior**
The footnotes is displayed with the link inside the footnote as written in the markdown.

**Screenshots**
<img width="1552" alt="Screenshot 2021-09-15 at 23 17 13" src="https://user-images.githubusercontent.com/18036223/133510883-c95488ba-2975-4d33-9ced-963844664f39.png">

**Desktop (please complete the following information):**
 - Operating system: macOS 11.6 
 - Ruby version: ruby 3.0.1

**Comment by maximevaillancourt** [comment]
Thanks for the report! Great catch. :pray: 

This is now fixed. You may update your fork to pull the latest changes on the `master` branch of this repository. :heavy_check_mark:

**Comment by dennisseidel** [comment]
Thank you for the super-fast fix 🙏 I'll check your fix out to get a better understanding of the codebase so next time I can make such small things a pull request 🙂 Really appreciate your effort!
