### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by Doom666** [maximevaillancourt/digital-garden-jekyll-template#86]
I was wondering on wethere there is a way to update  the last changes you have done, besides copy and pasting the code in my site.

**Comment by maximevaillancourt** [comment]
Of course. Follow these instructions to update your fork:

https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

**Comment by Doom666** [comment]
The repository is private, maybe thatçs why I dont see the fetch upstream option?

**Comment by maximevaillancourt** [comment]
Ah, maybe. The manual option described on GitHub's documentation page should still work though.

Out of curiosity, do you see the "fetch upstream" option on this public repository of yours?
https://github.com/Doom666/digital-garden
